/**
 * Guardrails — post-pipeline validation + flag generation.
 *
 * Run AFTER scope extraction + line matching + narrative writing. Surface flags to the HITL review UI.
 *
 * Checks:
 *  1. confidenceFlags — items with confidence < CONFIDENCE_THRESHOLD get needs_review=true (not auto-included in total).
 *  2. totalRangeCheck — total < $8K or > $120K (onboarding doc range) → blocking flag.
 *  3. totalDeviationCheck — total < 0.5× or > 2× $28K avg → non-blocking advisory flag.
 *  4. hallucinationCheck — narrative may NOT cite items/$amounts not in matched line items. Returns offending substrings.
 */

import {
  CONFIDENCE_THRESHOLD,
  PROJECT_VALUE_AVG,
  PROJECT_VALUE_MAX,
  PROJECT_VALUE_MIN,
  type PricingItem,
  type ProposalFlag,
} from "@/lib/types";
import type { LineMatchResult } from "@/lib/agents/line-matcher";

export type ScoredLineItem = {
  scope_description: string;
  pricing_item_id: string | null;
  quantity: number;
  unit_price: number;
  subtotal: number;
  confidence: number;
  needs_review: boolean;
};

/** Build the priced line item list + apply confidence threshold. */
export function buildScoredLineItems(matches: LineMatchResult[], catalog: PricingItem[]): ScoredLineItem[] {
  return matches.map((m) => {
    const pricing = m.pricing_item_id ? catalog.find((c) => c.id === m.pricing_item_id) : undefined;
    const unitPrice = pricing?.unit_price ?? 0;
    const subtotal = unitPrice * m.scope_item.quantity;
    const needsReview = m.confidence < CONFIDENCE_THRESHOLD || !pricing;
    return {
      scope_description: m.scope_item.description,
      pricing_item_id: m.pricing_item_id,
      quantity: m.scope_item.quantity,
      unit_price: unitPrice,
      subtotal: needsReview ? 0 : subtotal, // exclude review items from total
      confidence: m.confidence,
      needs_review: needsReview,
    };
  });
}

/** Sum subtotals (review items excluded). */
export function calculateTotal(items: ScoredLineItem[]): number {
  return items.reduce((sum, i) => sum + i.subtotal, 0);
}

/** All flags generated by the pipeline. */
export function generateFlags(items: ScoredLineItem[], total: number, narrative: string, catalog: PricingItem[]): ProposalFlag[] {
  const flags: ProposalFlag[] = [];

  // Low-confidence items
  for (const item of items) {
    if (item.needs_review) {
      flags.push({
        type: "low_confidence_item",
        message: `"${item.scope_description}" needs review (confidence: ${item.confidence.toFixed(2)}). Excluded from total.`,
      });
    }
  }

  // Total range (blocking-style flag — UI can still allow approval with explicit override)
  if (total < PROJECT_VALUE_MIN) {
    flags.push({
      type: "total_out_of_range",
      message: `Total $${total.toFixed(0)} is below Greenscape's typical floor ($${PROJECT_VALUE_MIN.toLocaleString()}). Review scope.`,
    });
  } else if (total > PROJECT_VALUE_MAX) {
    flags.push({
      type: "total_out_of_range",
      message: `Total $${total.toFixed(0)} is above Greenscape's typical ceiling ($${PROJECT_VALUE_MAX.toLocaleString()}). Review scope.`,
    });
  }

  // Deviation from average (advisory)
  if (total >= PROJECT_VALUE_MIN && total <= PROJECT_VALUE_MAX) {
    const ratio = total / PROJECT_VALUE_AVG;
    if (ratio < 0.5 || ratio > 2.0) {
      flags.push({
        type: "total_deviation",
        message: `Total $${total.toFixed(0)} is ${ratio.toFixed(1)}× the company average ($${PROJECT_VALUE_AVG.toLocaleString()}). Confirm scope.`,
      });
    }
  }

  // Hallucination check on narrative
  const hallucinated = detectHallucinatedItems(narrative, items, catalog);
  if (hallucinated.length > 0) {
    flags.push({
      type: "hallucination_blocked",
      message: `Narrative references items not in matched line items: ${hallucinated.join(", ")}. Regenerate narrative.`,
    });
  }

  return flags;
}

/**
 * Detect specific dollar amounts or item names in narrative that don't appear in matched items.
 *
 * Heuristic — conservative. Catches obvious hallucinations (made-up prices, made-up product names)
 * without false-flagging generic language ("we'll include lighting throughout").
 */
function detectHallucinatedItems(narrative: string, items: ScoredLineItem[], catalog: PricingItem[]): string[] {
  const violations: string[] = [];

  // 1. Dollar amounts: any $X,XXX in narrative must roughly match a subtotal or the total.
  const dollarMatches = narrative.match(/\$\s?[\d,]+(?:\.\d{1,2})?/g) ?? [];
  const allowedAmounts = new Set<string>();
  for (const item of items) {
    allowedAmounts.add(formatDollar(item.subtotal));
    allowedAmounts.add(formatDollar(item.unit_price));
  }

  for (const dollarText of dollarMatches) {
    const normalized = dollarText.replace(/\s/g, "");
    const number = Number(normalized.replace(/[$,]/g, ""));
    if (!Number.isFinite(number)) continue;
    if (number < 100) continue; // ignore small amounts (e.g., "$50 service fee" phrasing)
    const matchesAllowed = Array.from(allowedAmounts).some((allowed) => {
      const allowedNum = Number(allowed.replace(/[$,]/g, ""));
      return Math.abs(allowedNum - number) <= Math.max(1, number * 0.02); // 2% tolerance
    });
    if (!matchesAllowed) {
      violations.push(dollarText);
    }
  }

  // 2. Item-name check: catalog items the narrative names by exact name but aren't in matched items.
  const matchedIds = new Set(items.map((i) => i.pricing_item_id).filter(Boolean));
  for (const catalogItem of catalog) {
    if (matchedIds.has(catalogItem.id)) continue;
    // Only flag if narrative names the catalog item AND a sufficiently specific token from it.
    // Use longest distinctive token (>5 chars).
    const distinctive = catalogItem.item_name
      .split(/\s+/)
      .find((t) => t.length > 5 && /^[A-Za-z]+$/.test(t));
    if (!distinctive) continue;
    if (narrative.toLowerCase().includes(distinctive.toLowerCase())) {
      // Only flag if catalog item is named by full phrase — reduces false positives on generic words.
      if (narrative.toLowerCase().includes(catalogItem.item_name.toLowerCase())) {
        violations.push(catalogItem.item_name);
      }
    }
  }

  return Array.from(new Set(violations));
}

function formatDollar(n: number): string {
  return "$" + Math.round(n).toLocaleString("en-US");
}
